app:
  name: html4email
  description: ${app.name} is application for generating content

logging:
  file: app.log

server:
  port: 8181
  tomcat:
    compression: on
    compressableMimeTypes: text/html,text/xml,text/css,text/plain,application/json,application/xml,application/javascrip


security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
  headers: false

spring:
  resources:
    cache-period: 259200

# Digest configuration
digest:
  contributeTo: "me@mail.com"
  companyName: "companyName"
  templateName: "digest.ftl"
  archiveHost: "http://idgst.info"

# Email config
email:
  replyTo: "m@main.com"
  sendTo: "m@main.com"
  login: "m@main.com"
  password: "secret"
  smtp:
    host: "smtp.mail.com"
    ttlsEnable: true